services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      DB_CONFIG: >
        {"dbtype": "postgres", "extra_details": {"conn_str": "postgresql://admin:admin@postgres:5432/guardz?sslmode=disable"}}
      POSTGRES_HOST: postgres
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: guardz
      POSTGRES_PORT: 5432
    depends_on:
      - postgres
    networks:
      - app-network

  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: guardz
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  pgdata:
    driver: local